name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        # Only log into Docker Hub on push to main (prevents PR failures if Secrets are empty)
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fashion_mlops:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fashion_mlops:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fashion_mlops:buildcache,mode=max

  deploy:
    name: Deploy to Local Computer (Self-Hosted)
    runs-on: self-hosted
    needs: build-and-push
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Log in to Docker Hub (Local)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Pull Latest Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fashion_mlops:latest
        
      - name: Stop and Remove Old Container
        continue-on-error: true
        shell: cmd
        run: |
          docker stop fashion-server
          docker rm fashion-server
          exit 0
          
      - name: Run New Container
        run: docker run -d -p 8000:8000 --name fashion-server --restart always ${{ secrets.DOCKERHUB_USERNAME }}/fashion_mlops:latest
